---
title: "03 Workflow with caret"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# some file setup parameters
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999) # display numbers in non-scientific format
```


```{r}
data_url <- "https://raw.githubusercontent.com/staehlo/mlr3_and_tidymodels/main/example_data_set.csv"
loans <- read.csv2(file = data_url, header = TRUE, sep = ",", dec=".")
rm(data_url)

# Preprocessing
loans$grade <- as.factor(loans$grade)
loans$home_ownership <- as.factor(loans$home_ownership)
loans$purpose <- as.factor(loans$purpose)
loans$grade_num <- match(loans$grade, LETTERS)
loans$monthly_payback <-round(loans$loan_amnt / loans$term, 2)
loans$term <- as.factor(loans$term) # for the classification task

# We will focus on people with an annual income below 200'000 USD
loans <- loans[loans$annual_inc < 200000,]

# We will ignore the three cases with no indicated home ownership
loans <- loans[loans$home_ownership != "NONE",]
loans <- droplevels(loans) # remove the no longer used "NONE" level
```

```{r}
library(caret)
set.seed(123)
rows_for_training <- createDataPartition(y = loans$int_rate,
                                         p = 0.80,
                                         list = FALSE)
train <- loans[rows_for_training,]
test <- loans[-rows_for_training,]
```

Regression
```{r}
caret.fit <- train(int_rate ~ loan_amnt + annual_inc + grade_num + home_ownership + purpose, data = train, method = "lm")

caret.fit
summary(caret.fit)
```

